# Generated by Django 6.0.6 on 2026-07-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_options_remove_product_discount_end_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='specificationvalue',
            unique_together={('specification', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='variantspecification',
            unique_together={('variant', 'specification')},
        ),
    ]
