# Generated by Django 6.0.6 on 2026-07-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_vat_included_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantspecification',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='SpecificationValue',
        ),
    ]
