# Generated by Django 6.0.6 on 2026-07-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cart_wishlist_cartitem_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='include_vat',
            field=models.BooleanField(default=False),
        ),
    ]
