# Generated by Django 6.0.6 on 2026-07-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_vat_inclusive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vat_included',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vat_inclusive',
        ),
    ]
