# Generated by Django 6.0.6 on 2026-07-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_product_vat_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_inclusive',
            field=models.BooleanField(default=False, verbose_name='Price includes VAT'),
        ),
    ]
