# Generated by Django 6.0.6 on 2026-07-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_discount_end_product_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_end',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_start',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured_deal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
