# Generated by Django 6.0.6 on 2026-07-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_product_discount_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='discount_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
