# Generated by Django 6.0.6 on 2026-07-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_productvariant_discount_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deal',
        ),
    ]
