# Generated by Django 6.0.6 on 2026-07-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_brand_slug_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AddField(
            model_name='brand',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='brands/banners/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            
        ),
        migrations.AddField(
            model_name='brand',
            name='founded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='headline',
            field=models.CharField(blank=True, help_text='Example: Official HP Store', max_length=200),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short introduction displayed on the brand page.'),
        ),
        migrations.AddField(
            model_name='brand',
            name='theme_color',
            field=models.CharField(default='#1E4FD8', help_text='Primary brand color in HEX.', max_length=7),
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='warranty',
            field=models.CharField(blank=True, help_text='Example: 12 Months Manufacturer Warranty', max_length=100),
        ),
        migrations.AddField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/logos/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, default=0, unique=True),
            preserve_default=False,
        ),
    ]
