# Generated by Django 6.0.6 on 2026-07-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_brand_options_brand_banner_brand_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
