# Generated by Django 6.0.6 on 2026-07-14 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_productvariant_variant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app.specification')),
            ],
            options={
                'ordering': ['position', 'value'],
            },
        ),
    ]
