# Generated by Django 6.0.6 on 2026-07-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat_inclusive',
            field=models.BooleanField(default=True, verbose_name='Price Includes VAT'),
        ),
    ]
