# Generated by Django 6.0.6 on 2026-07-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('home', 'Homepage'), ('deal', 'Deals'), ('category', 'Category'), ('category_global', 'All Categories'), ('category_slider', 'Category Slider'), ('brand', 'Brand'), ('promo', 'Promotion')], max_length=20),
        ),
    ]
