# Generated by Django 6.0.6 on 2026-07-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_banner_banner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended')], default='draft', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='deal_campaigns/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('home', 'Homepage'), ('deal', 'Deals'), ('category', 'Specific Category Banner'), ('category_global', 'All Categories Banner'), ('category_slider', 'Category Slider'), ('brand', 'Brand'), ('promo', 'Promotion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='app.category'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='deal_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='app.dealcampaign'),
        ),
    ]
