# Generated by Django 6.0.6 on 2026-07-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_dealcampaign_alter_banner_banner_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealcampaign',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount'), ('price', 'Fixed Price')], default='percent', max_length=20),
        ),
        migrations.AddField(
            model_name='dealcampaign',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dealcampaign',
            name='holder_image',
            field=models.ImageField(default=0, upload_to='campaigns/holders/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealcampaign',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='deal_campaigns', to='app.productvariant'),
        ),
        migrations.AddField(
            model_name='dealcampaign',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dealcampaign',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/banners/'),
        ),
    ]
