# Generated by Django 6.0.6 on 2026-07-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_analyticsevent_productanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=200)),
                ('reviewer_photo', models.URLField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField()),
                ('google_review_id', models.CharField(max_length=255, unique=True)),
                ('review_time', models.DateTimeField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-review_time', '-created_at'],
            },
        ),
    ]
