# Generated by Django 6.0.6 on 2026-07-18 03:18

from django.db import migrations, models

from django.utils import timezone
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_googlereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'uploaded_at']},
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
   
        migrations.AddField(
            model_name='productimage',
            name='uploaded_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=timezone.now,
    ),
            preserve_default=False,
),
    ]