# Generated by Django 6.0.6 on 2026-07-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='reading_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
