# Generated by Django 6.0.6 on 2026-07-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wordpress_images',
            field=models.TextField(blank=True, default=''),
        ),
    ]
