# Generated by Django 6.0.6 on 2026-08-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_product_wordpress_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
